# Generated by Django 3.1.14 on 2022-12-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_pokemon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
