# Generated by Django 3.1.14 on 2022-12-02 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20221202_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ancestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
    ]
